# Site settings
author: decent-scraper-1450
title: 
header-img: img/home-bg.png
email: jaimealba1574@gmail.com
copyright_name: decent-scraper-1450
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mindtripp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
